name: mr_toolkit
channels:
  - conda-forge
  - defaults
dependencies:
 - python>=3.8
 - numpy<1.24
 - msmtools
 - tqdm
 - rich
 - deeptime
 - sphinx
 - sphinx_rtd_theme>=1.0
 - nbsphinx
 - pandas
 - pyemma
 - pytest
 - pytest-cov
 - jupyterlab
 - ipywidgets
 - pip
 - pip:
     - synd
     - sigopt
     - .
