name: mr_toolkit
channels:
  - conda-forge
  - defaults
dependencies:
 - numpy<1.24
 - msmtools
 - tqdm
 - rich
 - deeptime
 - sphinx
 - sphinx_rtd_theme
 - pandas
 - pyemma
 - pip
 - pip:
     - pytest
     - pytest-cov
     - synd
     - .